//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibliothek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buch
    {
        public int Id { get; set; }
        public string Titel { get; set; }
        public string Autor { get; set; }
        public string ISBN { get; set; }
    }
}
