//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibliothek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutzer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
        public string Login { get; set; }
        public string Passwort { get; set; }
        public bool IstAktiv { get; set; }
    }
}
